services:
  nginx:
    build:
      context: ./nginx
    container_name: app_nginx
    ports:
      - '8001:80'
    volumes:
      - ../src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - nginx_logs:/var/log/nginx
    depends_on:
      - php82
    networks:
      - app_network

  php82:
    build:
      context: ./php/php82
    container_name: app_php82
    volumes:
      - ../src:/var/www/html
      - ./php/php82/php.ini:/usr/local/etc/php/conf.d/custom.ini
    working_dir: /var/www/html
    networks:
      - app_network

  mysql:
    image: mysql:8.2
    container_name: app_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: app_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      PMA_ARBITRARY: 1
      UPLOADLIMIT: 300M
    ports:
      - '8081:80'
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app_network

volumes:
  mysql_data:
  nginx_logs:
  php_logs:
  mysql_logs:

networks:
  app_network:
    driver: bridge
